export const TARIFFS = [
  {
    id: "1",
    name: "Первая доза",
    duration: "1 месяц",
    price: 5000,
    originalPrice: null,
    note: "Попробуй",
    popular: false,
    features: ["Доступ ко всем играм", "Личный кабинет", "История сделок"],
  },
  {
    id: "2",
    name: "Брошу в любой момент",
    duration: "3 месяца",
    price: 9000,
    originalPrice: 15000,
    note: "−40%",
    popular: false,
    features: ["Доступ ко всем играм", "Личный кабинет", "История сделок", "Сертификаты"],
  },
  {
    id: "3",
    name: "Вы не понимаете",
    duration: "Клубный",
    price: 15000,
    originalPrice: 30000,
    note: "Хит продаж",
    popular: true,
    features: ["Доступ ко всем играм", "Личный кабинет", "История сделок", "Сертификаты", "Питч-сессии", "Приоритетное место"],
  },
  {
    id: "4",
    name: "Зависимость",
    duration: "1 год",
    price: 24000,
    originalPrice: 60000,
    note: "−60%",
    popular: false,
    features: ["Доступ ко всем играм", "Личный кабинет", "История сделок", "Сертификаты", "Питч-сессии", "VIP-статус"],
  },
];

export const GAMES = [
  {
    id: "1",
    title: "Бартерия #13 · Весенняя",
    description: "Большое весеннее мероприятие с расширенным составом",
    location: "Москва, Loft Hall",
    date: "2026-03-28T18:00:00",
    status: "open" as const,
    maxParticipants: 40,
    currentParticipants: 28,
    pitchDuration: 120,
  },
  {
    id: "2",
    title: "Бартерия #14 · IT-спец",
    description: "Тематическая игра для IT-специалистов и стартаперов",
    location: "Москва, Digital October",
    date: "2026-04-15T18:30:00",
    status: "draft" as const,
    maxParticipants: 30,
    currentParticipants: 0,
    pitchDuration: 120,
  },
  {
    id: "3",
    title: "Бартерия #12 · Зимняя",
    description: "Уютная зимняя игра в камерной атмосфере",
    location: "Москва, Кофемания",
    date: "2026-02-14T18:00:00",
    status: "done" as const,
    maxParticipants: 25,
    currentParticipants: 25,
    pitchDuration: 120,
  },
];

export const PARTICIPANTS = [
  { id: "1", name: "Алексей Петров", username: "@alexey_p", about: "Дизайнер интерфейсов", balance: 45000, deals: 8, avatar: null },
  { id: "2", name: "Мария Козлова", username: "@mashakoz", about: "SMM-продвижение", balance: 32000, deals: 6, avatar: null },
  { id: "3", name: "Дмитрий Волков", username: "@dimawolf", about: "Копирайтинг и контент", balance: 28000, deals: 5, avatar: null },
  { id: "4", name: "Елена Сидорова", username: "@elena_sid", about: "Юридические консультации", balance: 55000, deals: 11, avatar: null },
  { id: "5", name: "Иван Новиков", username: "@ivan_nov", about: "Фотосъёмка", balance: 20000, deals: 4, avatar: null },
  { id: "6", name: "Ольга Морозова", username: "@olga_m", about: "Бухгалтерия", balance: 38000, deals: 7, avatar: null },
  { id: "7", name: "Сергей Ким", username: "@sergey_kim", about: "Разработка ботов", balance: 62000, deals: 13, avatar: null },
  { id: "8", name: "Анна Белова", username: "@anna_bel", about: "Массаж и wellness", balance: 41000, deals: 9, avatar: null },
];

export const TRANSACTIONS = [
  { id: "1", type: "transfer" as const, from: "Сергей Ким", to: "Мария Козлова", amount: 5000, note: "SMM для Telegram-канала", time: new Date(Date.now() - 3 * 60000) },
  { id: "2", type: "bank_in" as const, from: null, to: "Алексей Петров", amount: 30000, amountRub: 3000, note: "Покупка Бартеров", time: new Date(Date.now() - 8 * 60000) },
  { id: "3", type: "transfer" as const, from: "Елена Сидорова", to: "Дмитрий Волков", amount: 8000, note: "Текст для лендинга", time: new Date(Date.now() - 15 * 60000) },
  { id: "4", type: "transfer" as const, from: "Анна Белова", to: "Сергей Ким", amount: 12000, note: "Разработка Telegram-бота", time: new Date(Date.now() - 22 * 60000) },
  { id: "5", type: "bank_in" as const, from: null, to: "Ольга Морозова", amount: 50000, amountRub: 5000, note: "Покупка Бартеров", time: new Date(Date.now() - 30 * 60000) },
  { id: "6", type: "transfer" as const, from: "Иван Новиков", to: "Елена Сидорова", amount: 15000, note: "Юридическая консультация по ИП", time: new Date(Date.now() - 40 * 60000) },
  { id: "7", type: "transfer" as const, from: "Мария Козлова", to: "Анна Белова", amount: 6000, note: "Массаж", time: new Date(Date.now() - 55 * 60000) },
  { id: "8", type: "bank_out" as const, from: "Дмитрий Волков", to: null, amount: 10000, amountRub: 1000, note: "Возврат Бартеров", time: new Date(Date.now() - 65 * 60000) },
];

export const CERTIFICATES = [
  { id: "1", seller: "Мария Козлова", buyer: "Сергей Ким", service: "SMM-продвижение Telegram-канала на 1 месяц", amount: 5000, status: "active" as const, createdAt: new Date(Date.now() - 3 * 60000) },
  { id: "2", seller: "Дмитрий Волков", buyer: "Елена Сидорова", service: "Написание текстов для лендинга (5 блоков)", amount: 8000, status: "activated" as const, createdAt: new Date(Date.now() - 86400000) },
  { id: "3", seller: "Сергей Ким", buyer: "Анна Белова", service: "Разработка Telegram-бота для записи клиентов", amount: 12000, status: "active" as const, createdAt: new Date(Date.now() - 22 * 60000) },
  { id: "4", seller: "Елена Сидорова", buyer: "Иван Новиков", service: "Юридическая консультация по регистрации ИП", amount: 15000, status: "activated" as const, createdAt: new Date(Date.now() - 172800000) },
  { id: "5", seller: "Анна Белова", buyer: "Мария Козлова", service: "3 сеанса массажа", amount: 6000, status: "active" as const, createdAt: new Date(Date.now() - 55 * 60000) },
];

export const PITCH_QUEUE = [
  { id: "1", name: "Алексей Петров", offerings: ["UX/UI дизайн", "Прототипирование", "Аудит интерфейсов"], status: "done" as const, order: 1 },
  { id: "2", name: "Мария Козлова", offerings: ["SMM-продвижение", "Контент-план", "Настройка таргета"], status: "done" as const, order: 2 },
  { id: "3", name: "Дмитрий Волков", offerings: ["Копирайтинг", "SEO-тексты", "Рерайт"], status: "active" as const, order: 3 },
  { id: "4", name: "Елена Сидорова", offerings: ["Юр. консультации", "Договоры", "Регистрация ИП/ООО"], status: "waiting" as const, order: 4 },
  { id: "5", name: "Иван Новиков", offerings: ["Фотосъёмка", "Обработка фото", "Предметная съёмка"], status: "waiting" as const, order: 5 },
  { id: "6", name: "Ольга Морозова", offerings: ["Бухгалтерия", "Налоговая отчётность", "Кадровый учёт"], status: "waiting" as const, order: 6 },
  { id: "7", name: "Сергей Ким", offerings: ["Telegram-боты", "Парсинг", "Автоматизация"], status: "waiting" as const, order: 7 },
  { id: "8", name: "Анна Белова", offerings: ["Массаж", "Wellness-консультации", "Йога"], status: "waiting" as const, order: 8 },
];

export const DASHBOARD_STATS = {
  totalParticipants: 25,
  totalDeals: 47,
  totalBarters: 842000,
  totalRubDeposited: 125000,
  totalRubWithdrawn: 18000,
  bartersInCirculation: 842000,
  dealsPerMinute: 2.3,
  avgDealSize: 17914,
  gameStartedAt: new Date(Date.now() - 90 * 60000),
  activityData: [
    { time: "18:00", deals: 0 },
    { time: "18:05", deals: 2 },
    { time: "18:10", deals: 5 },
    { time: "18:15", deals: 3 },
    { time: "18:20", deals: 7 },
    { time: "18:25", deals: 4 },
    { time: "18:30", deals: 8 },
    { time: "18:35", deals: 6 },
    { time: "18:40", deals: 9 },
    { time: "18:45", deals: 5 },
    { time: "18:50", deals: 11 },
    { time: "18:55", deals: 7 },
    { time: "19:00", deals: 4 },
    { time: "19:05", deals: 6 },
    { time: "19:10", deals: 8 },
    { time: "19:15", deals: 3 },
    { time: "19:20", deals: 5 },
    { time: "19:25", deals: 9 },
  ],
  certsByStatus: {
    active: 18,
    activated: 24,
    cancelled: 5,
  },
};

export const CURRENT_USER = {
  id: "7",
  telegramId: 123456789,
  firstName: "Сергей",
  lastName: "Ким",
  username: "@sergey_kim",
  about: "Разработка Telegram-ботов, парсинг данных, автоматизация бизнес-процессов",
  role: "user" as const,
  tariff: TARIFFS[2],
  tariffExpiresAt: new Date("2026-06-15"),
  offerings: ["Telegram-боты", "Парсинг данных", "Автоматизация", "Web-скрапинг", "API-интеграции"],
  currentGameBalance: 62000,
  totalDeals: 13,
};
